# Generated by Django 5.1.5 on 2025-02-23 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycollection', '0003_collectiontag_mycollection_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycollection',
            name='tag',
            field=models.ManyToManyField(blank=True, to='mycollection.collectiontag'),
        ),
        migrations.CreateModel(
            name='CollectionFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mycollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycollection.mycollection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mycollection')},
            },
        ),
    ]
